import { CoreMenu } from '@core/types';

export const menu: CoreMenu[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    translate: 'menu.dashboard.collapsible',
    type: 'item',
    role: ['student'],
    icon: 'home',
    url: 'dashboard',
  },
  {
    id: 'users',
    type: 'section',
    title: 'Content Management',
    translate: 'menu.content_management',
    icon: 'package',
    children: [
      {
        id: '1',
        title: 'Admins',
        translate: 'menu.admin_management',
        type: 'collapsible',
        icon: 'users',
        children: [
          {
            id: 'admins',
            title: 'Admins',
            translate: 'menu.admin_list',
            type: 'item',
            icon: 'circle',
            url: 'users/admins/list',
          },
          {
            id: 'permissions',
            title: 'Permissions',
            translate: 'menu.permissions',
            type: 'item',
            icon: 'circle',
            url: 'users/permissions/list',
          },
        ],
      },
      {
        id: '2',
        title: 'Compounds',
        translate: 'menu.compounds',
        type: 'item',
        icon: 'codesandbox',
        url: 'users/compounds/list',
      },
      {
        id: '22',
        title: 'Coorperates',
        translate: 'menu.coorperates',
        type: 'item',
        icon: 'codesandbox',
        url: 'users/coorperates/list',
      },
      {
        id: '3',
        title: 'Customers',
        translate: 'menu.app_users',
        type: 'item',
        icon: 'users',
        url: 'users/customers/list',
      },
      {
        id: '4',
        title: 'Visitor',
        translate: 'menu.compound_visitors',
        type: 'item',
        icon: 'user-check',
        url: 'users/visitors/list',
      },
      {
        id: 'transactions',
        title: 'Transactions List',
        translate: 'menu.APP.TRANSACTIONS',
        type: 'item',
        icon: 'credit-card',
        url: 'apps/transaction-history/list',
      },
      {
        id: 'notifications',
        title: 'Notification List',
        translate: 'menu.APP.NOTIFICATIONS',
        type: 'item',
        icon: 'bell',
        url: 'apps/notifications/list',
      },
      {
        id: 'terms_and_conditions',
        title: 'Terms and Conditions',
        translate: 'menu.APP.TERMS_AND_CONDITIONS',
        type: 'item',
        icon: 'file-text',
        url: 'apps/termsAndConditions/view/1',
      },
      {
        id: 'help_and_support',
        title: 'Help and Support',
        translate: 'menu.APP.HELP_AND_SUPPORT',
        type: 'item',
        icon: 'life-buoy',
        url: 'apps/support/list',
      }
    ],
  },
];
